(function(h,R,t){"use strict";var c={exports:{}},l={};/**
 * @license React
 * react-jsx-runtime.production.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */var f;function m(){if(f)return l;f=1;var r=Symbol.for("react.transitional.element"),d=Symbol.for("react.fragment");function x(S,e,n){var a=null;if(n!==void 0&&(a=""+n),e.key!==void 0&&(a=""+e.key),"key"in e){n={};for(var u in e)u!=="key"&&(n[u]=e[u])}else n=e;return e=n.ref,{$$typeof:r,type:S,key:a,ref:e!==void 0?e:null,props:n}}return l.Fragment=d,l.jsx=x,l.jsxs=x,l}var p;function E(){return p||(p=1,c.exports=m()),c.exports}var o=E();const T=[{id:"1",title:"Summer Sale",description:"Up to 50% off on selected items",color:"#0b6f6a"},{id:"2",title:"New Arrivals",description:"Check out the latest collection",color:"#7c3aed"},{id:"3",title:"Free Shipping",description:"On all orders over $50",color:"#b45309"}];function _({items:r=T}){return o.jsxs(t.View,{style:i.wrapper,children:[o.jsx(t.Text,{style:i.heading,children:"Promotions"}),o.jsx(t.ScrollView,{horizontal:!0,showsHorizontalScrollIndicator:!1,style:i.scroll,children:r.map(d=>o.jsx(j,{item:d},d.id))})]})}function j({item:r}){return o.jsxs(t.View,{style:[i.card,{backgroundColor:r.color}],children:[o.jsx(t.Text,{style:i.cardTitle,children:r.title}),o.jsx(t.Text,{style:i.cardDesc,children:r.description})]})}const i=t.StyleSheet.create({wrapper:{marginTop:14,padding:16,borderColor:"#d6dde8",borderRadius:8,borderWidth:1,backgroundColor:"#ffffff"},heading:{color:"#24364a",fontSize:16,fontWeight:"800",marginBottom:12},scroll:{flexDirection:"row"},card:{borderRadius:8,padding:16,marginRight:12,width:200,minHeight:90,justifyContent:"center"},cardTitle:{color:"#ffffff",fontSize:15,fontWeight:"800",marginBottom:6},cardDesc:{color:"rgba(255,255,255,0.85)",fontSize:13}});let s=null;window.__MICRO_APP_LIFECYCLE__={async bootstrap(){},async mount(r){s=R.createRoot(r.container),s.render(h.createElement(_,{items:r.props.items}))},async unmount(){s==null||s.unmount(),s=null}}})(React,ReactDOMClient,ReactNativeWeb);
